name: Compilation checker

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Go setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Compile
      run: |
        set -e # will exit on 1st error
        for file in $(find . -name '*.go'); do
          go build $file
        done
    - name: Check compilation
      if: ${{ success() }}
      run: echo "compiled successfully"
    - name: Commit on main
      if : ${{ success }}
      run: |
        git add -A
        git commit -m "minor"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
