name: Compilation checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Go setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Compile
      run: |
        set -e # will exit on 1st error
        for file in $(find . -name '*.go'); do
          go build $file
        done
    - name: Check compilation
      if: ${{ success() }}
      run: echo "compiled successfully"
    - name: PUSH
      uses: EndBug/add-and-commit@v9
      with:
        # branch: main
        message: "daily"
        github_token: ${{ secrets.GITHUB_TOKEN }}
